# Generated by Django 4.2.29 on 2026-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'date', 'service_type')},
        ),
    ]
